Parameters:
  EnvType:
    Description: Select an Environment 
    Type: String 
    AllowedValues: [PROD , DEV]

Conditions: 
  CreateProdResources: !Equals [ !Ref EnvType, PROD ] 
  CreateDevResources: !Equals [ !Ref EnvType, DEV ]

Mappings:
  AWSAMIs:
    us-east-1:
      AMI: ami-6871a115
      SUBNET: subnet-f16d73dd
      SGNAME: 
        - sg-80d272f2
    us-east-2:
      AMI: ami-03291866
      SUBNET: subnet-dcf4e1b5
      SGNAME: 
       - sg-b10a9ed9

Resources:
  Ec2InstancePROD: 
    Type: "AWS::EC2::Instance"
    Condition: CreateProdResources
    Properties: 
      ImageId: !FindInMap [AWSAMIs, !Ref "AWS::Region", AMI]
      InstanceType: t2.micro
      SubnetId: !FindInMap [AWSAMIs, !Ref "AWS::Region", SUBNET]
      Tags:
        - Key: Name
          Value: Sample 
      SecurityGroupIds: !FindInMap [AWSAMIs, !Ref "AWS::Region", SGNAME]
      KeyName: devops-prod 

  Ec2InstanceDEV: 
    Type: "AWS::EC2::Instance"
    Condition: CreateDevResources
    Properties: 
      ImageId: !FindInMap [AWSAMIs, !Ref "AWS::Region", AMI]
      InstanceType: t2.micro
      SubnetId: !FindInMap [AWSAMIs, !Ref "AWS::Region", SUBNET]
      Tags:
        - Key: Name
          Value: Sample 
      SecurityGroupIds: !FindInMap [AWSAMIs, !Ref "AWS::Region", SGNAME]
      KeyName: devops-dev 